### ISSUE TITLE
Breaking: Redirects error prevents User profile edits

### ISSUE THREAD

**Issue by john-henry** [barrelstrength/craft-sprout-redirects#11]
### Description
When editing any user profile I get he following error

> Invalid Configuration – yii\base\InvalidConfigException
> Unable to locate message source for category 'sprout-sitemaps'.

### Steps to reproduce

1.Click on any user to edit their profile including your own
2.

### Additional info

- Craft version:3.1.30
- PHP version:7.2
- Database driver & version:5.7
- Plugins & versions:Sprout Redirects 1.0.1 (trial) and alos Pro on a production site

**Comment by andrelopez** [comment]
Hi @john-henry 

We just released Sprout Redirects v1.0.2 with a fix for this issue.

Thanks
