### ISSUE TITLE
Frontend redirects are now ignoring DB_TABLE_PREFIX environment variable

### ISSUE THREAD

**Issue by existenceltd** [barrelstrength/craft-sprout-redirects#18]
### Description (screenshots, logs, ...)
After upgrading to 1.2.0 when attempting to follow a redirect on a site that is using craft_ as a prefix the request ignores the prefix and then gives the following error
Uncaught PDOException: SQLSTATE[42S02]: Base table or view not found: 1146 Table 'xxx.sproutseo_redirects' doesn't exist

### Steps to reproduce

1. Upgrade a Craft2 site to Craft3 and keep the original prefixes and use the DB_TABLE_PREFIX=craft_ .env variable
2. Upgrade Sprout SEO Redirects from 1.1.2 to 1.2.0

### Additional info

- Craft version: Craft Pro 3.3.15
- PHP version: 7.3
- Database driver & version:   MySQL 5.6 (on fortrabbit)

_For some issues, we may request that you send the following items to Support <sprout@barrelstrengthdesign.com>. If you feel your issue may fall in that category, feel free to send things over after you post this issue and reference the issue in your email._

- `composer.json`
- `storage/logs/web.log` (or a zip of the whole log folder)
- An export of your database (or, if you can't share the whole db, the specific Sprout tables)

**Comment by BenParizek** [comment]
Thanks for reporting @existenceltd. We'll get this fixed.

**Comment by BenParizek** [comment]
@existenceltd This is resolved in Sprout Redirects v1.2.1 and Sprout SEO v4.2.5

**Comment by existenceltd** [comment]
Thank you so much Ben. I really appreciate this fast response. 

Updating now.
