### ISSUE TITLE
Issues from startup, ignoring DB_TABLE_PREFIX

### ISSUE THREAD

**Issue by JustJarethB** [barrelstrength/craft-sprout-redirects#19]
### Description (screenshots, logs, ...)
There is a pre-existing (and closed) issue here https://github.com/barrelstrength/craft-sprout-redirects/issues/18
which I believe is related, however our install version is above the noted patch version. From installing sprout redirect I have been unable to access the cp pages associated.

Selecting `Sprout Redirects` from the side navigation results in the following error:
```
SQLSTATE[42S22]: Column not found: 1054 Unknown column 'sproutseo_redirects.dateLastUsed' in 'field list'
```
I have looked in the database and we have a table named `craft_sproutseo_redirects`

Selecting `Settings` from the Settings > Plugins > Sprout Redirects results in a 404
```
Unable to find the template “sprout-redirects/settings”.
```

### Steps to reproduce

1. Create project with DB table prefix set (in our case, `craft_`)
2. Install plugin and attempt to use

### Additional info

- Craft version: 3.2.8
- PHP version: 7.1.26
- Database driver & version:  MySQL 5.7.25
- Plugins & versions: "barrelstrength/sprout-redirects": "1.2.2"

_For some issues, we may request that you send the following items to Support <sprout@barrelstrengthdesign.com>. If you feel your issue may fall in that category, feel free to send things over after you post this issue and reference the issue in your email._

- `composer.json`
- `storage/logs/web.log` (or a zip of the whole log folder)
- An export of your database (or, if you can't share the whole db, the specific Sprout tables)

**Comment by BenParizek** [comment]
Thanks @JustJarethB 

We'll get a fix out for this soon.

**Comment by BenParizek** [comment]
Related: https://github.com/barrelstrength/craft-sprout-base-redirects/pull/1

**Comment by BenParizek** [comment]
@JustJarethB This issue is resolved in the latest release. Thanks for reporting.

**Comment by JustJarethB** [comment]
Thanks @BenParizek! I just updated to 1.2.3.2 which was the latest showing update, and the same issue is showing. What number am I looking for?

**Comment by BenParizek** [comment]
@JustJarethB That's the latest. Did you reinstall? I believe the error you ran into was an issue with the Install migration so you may need to reinstall to get things corrected. 

If I'm missing something and you have data you don't want to lose, I may need more context such as your log files or db to dig in further: sprout@barrelstrengthdesign.com
