### ISSUE TITLE
Cannot view list of redirects in Craft 3.4.3

### ISSUE THREAD

**Issue by nomadic-code** [barrelstrength/craft-sprout-redirects#21]
### Description (screenshots, logs, ...)

I updated to Craft 3.4.3 and noticed that I cannot see the list of redirects that have been added via the plugin. The data is still there, as the redirects function as intended, however the list is empty. Upon opening the inspector I noticed there is a js error, wondering if perhaps this is the culprit? "Cannot read property 'addOptions' of null"

![sproutredirect](https://user-images.githubusercontent.com/4020356/73891584-31430400-483a-11ea-8105-fa52324c7158.jpg)

### Steps to reproduce

1. Selecting the 'Redirects' menu item

### Additional info

- Craft version: 3.4.3
- PHP version: 7.3
- Database driver & version:  MySQL 5.7.19
- Plugins & versions:
Sprout Redirects 1.2.4.1
Super Table 2.4.4
SEOmatic 3.2.41
Redactor 2.5.0
Migration Assistant 3.1.6
Imager v2.3.1
GeoMate v1.1.0.2
Element API 2.6.0

_For some issues, we may request that you send the following items to Support <sprout@barrelstrengthdesign.com>. If you feel your issue may fall in that category, feel free to send things over after you post this issue and reference the issue in your email._

- `composer.json`
- `storage/logs/web.log` (or a zip of the whole log folder)
- An export of your database (or, if you can't share the whole db, the specific Sprout tables)

**Comment by BenParizek** [comment]
Thanks @nomadic-code 

We've just released Sprout Redirects v1.3.0 that adds Craft 3.4 support and resolves this issue.
