### ISSUE TITLE
Multisite Redirects to Main Site

### ISSUE THREAD

**Issue by JustJarethB** [barrelstrength/craft-sprout-redirects#24]
### Description (screenshots, logs, ...)
We have a 2 site setup. The redirects set up on the second site redirect to the first site (i.e. `b.com/foo => a.com/bar` )

### Steps to reproduce

1. Create Multisite
2. Add redirect for secondary site
3. Test Redirect

### Additional info

- Craft version: Craft Pro 3.4.5
- PHP version: 7.3.14
- Database driver & version:  MySQL 5.5.62
- Plugins & versions:
Campaign	1.13.2
Embedded Assets	2.2.1
Empty Coalesce	1.0.6
Freeform	3.6.2
Imager	v2.4.0
Inventory	2.0.3
Maps	3.7.7
Position Fieldtype	1.0.14
Redactor	2.6.0.1
SEOMate	1.1.2
Sprout Redirects	1.3.1

<img src="https://frontapp.com/assets/img/favicons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_1epfn)

**Comment by BenParizek** [comment]
Thanks for reporting @JustJarethB. I'll let you know when we have a fix out.

**Comment by BenParizek** [comment]
@JustJarethB This is resolved in the latest release v1.3.2.
