### ISSUE TITLE
Unable to update to latest version

### ISSUE THREAD

**Issue by MattWilcox** [barrelstrength/craft-sprout-redirects#30]
### Unable to update to latest version

```
Output:
<warning>Package "craftcms/vue-asset" listed for update is not installed. Ignoring.</warning>
<warning>Package "danielstjules/stringy" listed for update is not installed. Ignoring.</warning>
Loading composer repositories with package information
Updating dependencies
Your requirements could not be resolved to an installable set of packages.
  Problem 1
    - Installation request for barrelstrength/sprout-redirects 1.5.2 -> satisfiable by barrelstrength/sprout-redirects[1.5.2].
    - Conclusion: don't install barrelstrength/sprout-base 5.2.0
    - barrelstrength/sprout-import 1.0.2 requires barrelstrength/sprout-base ^5.0.0 -> satisfiable by barrelstrength/sprout-base[5.1.2, 5.0.0, 5.0.1, 5.0.2, 5.0.3, 5.0.4, 5.0.5, 5.0.7, 5.0.9, 5.1.0, 5.1.1, 5.1.3, 5.2.0].
    - barrelstrength/sprout-import 1.0.2 requires barrelstrength/sprout-base ^5.0.0 -> satisfiable by barrelstrength/sprout-base[5.1.2, 5.0.0, 5.0.1, 5.0.2, 5.0.3, 5.0.4, 5.0.5, 5.0.7, 5.0.9, 5.1.0, 5.1.1, 5.1.3, 5.2.0].
    - barrelstrength/sprout-import 1.0.2 requires barrelstrength/sprout-base ^5.0.0 -> satisfiable by barrelstrength/sprout-base[5.1.2, 5.0.0, 5.0.1, 5.0.2, 5.0.3, 5.0.4, 5.0.5, 5.0.7, 5.0.9, 5.1.0, 5.1.1, 5.1.3, 5.2.0].
    - Can only install one of: barrelstrength/sprout-base[6.0.0, 5.1.2].
    - Can only install one of: barrelstrength/sprout-base[5.0.9, 6.0.0].
    - Can only install one of: barrelstrength/sprout-base[5.1.0, 6.0.0].
    - Can only install one of: barrelstrength/sprout-base[5.1.1, 6.0.0].
    - Can only install one of: barrelstrength/sprout-base[5.1.2, 6.0.0].
    - Can only install one of: barrelstrength/sprout-base[5.1.3, 6.0.0].
    - Can only install one of: barrelstrength/sprout-base[6.0.0, 5.1.2].
    - Can only install one of: barrelstrength/sprout-base[5.0.0, 6.0.0].
    - Can only install one of: barrelstrength/sprout-base[5.0.1, 6.0.0].
    - Can only install one of: barrelstrength/sprout-base[5.0.2, 6.0.0].
    - Can only install one of: barrelstrength/sprout-base[5.0.3, 6.0.0].
    - Can only install one of: barrelstrength/sprout-base[5.0.4, 6.0.0].
    - Can only install one of: barrelstrength/sprout-base[5.0.5, 6.0.0].
    - Can only install one of: barrelstrength/sprout-base[5.0.7, 6.0.0].
    - barrelstrength/sprout-redirects 1.5.2 requires barrelstrength/sprout-base ^6.0.0 -> satisfiable by barrelstrength/sprout-base[6.0.1, 6.0.0].
    - Conclusion: don't install barrelstrength/sprout-base 6.0.1
    - Installation request for barrelstrength/sprout-import 1.0.2 -> satisfiable by barrelstrength/sprout-import[1.0.2].
<warning>Running update with --no-dev does not mean require-dev is ignored, it just means the packages will not be installed. If dev requirements are blocking the update you have to resolve those problems.</warning>
```

### Steps to reproduce

1. Attempt to run the plugin update

#### Application Info
PHP version	7.2.24
OS version	Linux 4.15.0-109-generic
Database driver & version	MySQL 5.7.30
Image driver & version	Imagick 3.4.3RC2 (ImageMagick 6.9.7-4)
Craft edition & version	Craft Pro 3.4.29
Yii version	2.0.35
Twig version	2.12.5
Guzzle version	6.5.5
Imagine version	1.2.3-dev

#### Plugins
Blitz	3.6.5
Dumper	2.0.0
Eager Beaver	1.0.4
Empty Coalesce	1.0.6
Feed Me	4.2.3
Field Manager	2.1.6
Imager	v2.4.0
Image Resizer	2.0.10
Inlin	2.1.1
Instagram Feed	1.0.5
Maps	3.8.4.1
Minify	1.2.10
Redactor	2.6.1
schema	1.0.3
SEOmatic	3.3.8
Similar	1.0.6
Sprout Import	1.0.2
Sprout Redirects	1.3.1
Table Maker	2.0.1
Twig Profiler	1.0.1

**Comment by BenParizek** [comment]
@MattWilcox A while back, when Craft purchased FeedMe, we discontinued Sprout Import and stopped updating it. Sprout Import plugin requires an older version of our shared sprout-base package (`barrelstrength/sprout-base ^5.0.0`). However, the latest version of Sprout Redirects requires a new major version of that shared base package (`barrelstrength/sprout-base ^6.0.0`).

Your options are:

- Upgrade to the last version of Sprout Redirects before it started requiring sprout-base `v6.0.0`
- Migrate whatever you're doing with Sprout Import to Craft's first-party FeedMe plugin and uninstall Sprout Import
- Hack Sprout Import for your project and update it to require sprout-base `^6.0.0` (and hope everything you are using continues to work)

Let me know if one of those options can work for you.

**Comment by MattWilcox** [comment]
Ahhh, thanks Ben - I've let another developer on our team know and let you know. Makes sense though.
