### ISSUE TITLE
Craft 3.5 after upgrade gives a 500 error - Call to a member function getAcceptsJson() on string

### ISSUE THREAD

**Issue by green17** [barrelstrength/craft-sprout-redirects#32]
Craft 3.5 after upgrade gives a 500 error - Call to a member function getAcceptsJson() on string

**Comment by BenParizek** [comment]
@green17 The Sprout plugins are not yet Craft 3.5 compatible.

More context on where things stand here:
https://github.com/barrelstrength/craft-sprout-forms/issues/521#issuecomment-685744505

And if you're daring (to which I'd recommend caution), a temporary fix that may not address other Craft 3.5 issues is discussed here: 
https://github.com/barrelstrength/craft-sprout-reports/issues/98#issuecomment-685710988

**Comment by green17** [comment]
Thanks, @BenParizek that done the trick. :-)
