### ISSUE TITLE
Server Error after changing redirect type from 404 to 301 and saving

### ISSUE THREAD

**Issue by tonioseiler** [barrelstrength/craft-sprout-redirects#34]
### Description (screenshots, logs, ...)

After opening up a 404 redirect, changing the type to 301 and then save, a screen with "Server Error apears". After that, the redirect disappeared.

### Steps to reproduce

1.
2.

### Additional info

- Craft version: 3.5
- PHP version: 7.4
- Database driver & version:  MySQL 5.5.5
- Plugins & versions:  Sprout Redirects | 1.5.2

_For some issues, we may request that you send the following items to Support <sprout@barrelstrengthdesign.com>. If you feel your issue may fall in that category, feel free to send things over after you post this issue and reference the issue in your email._

- `composer.json`
- `storage/logs/web.log` (or a zip of the whole log folder)
- An export of your database (or, if you can't share the whole db, the specific Sprout tables)

**Comment by tonioseiler** [comment]
In fact i just found out: I cannot edit any redirects. After saving, an error message appears...

**Comment by tonioseiler** [comment]
Here is my log


2021-01-27 14:07:48 [-][1][a4254be4bf366ba929230bda31ea5b4e][error][craft\errors\ElementNotFoundException] craft\errors\ElementNotFoundException: No element exists with the ID '38112' in /home/httpd/vhosts/reatch.ch/reatch.ch/vendor/craftcms/cms/src/services/Elements.php:2327
Stack trace:
#0 /home/httpd/vhosts/reatch.ch/reatch.ch/vendor/craftcms/cms/src/services/Elements.php(755): craft\services\Elements->_saveElementInternal(Object(barrelstrength\sproutbaseredirects\elements\Redirect), true, true, true)
#1 /home/httpd/vhosts/reatch.ch/reatch.ch/vendor/barrelstrength/sprout-base-redirects/src/controllers/RedirectsController.php(220): craft\services\Elements->saveElement(Object(barrelstrength\sproutbaseredirects\elements\Redirect))
#2 [internal function]: barrelstrength\sproutbaseredirects\controllers\RedirectsController->actionSaveRedirect()
#3 /home/httpd/vhosts/reatch.ch/reatch.ch/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#4 /home/httpd/vhosts/reatch.ch/reatch.ch/vendor/yiisoft/yii2/base/Controller.php(180): yii\base\InlineAction->runWithParams(Array)
#5 /home/httpd/vhosts/reatch.ch/reatch.ch/vendor/craftcms/cms/src/web/Controller.php(190): yii\base\Controller->runAction('save-redirect', Array)
#6 /home/httpd/vhosts/reatch.ch/reatch.ch/vendor/yiisoft/yii2/base/Module.php(528): craft\web\Controller->runAction('save-redirect', Array)
#7 /home/httpd/vhosts/reatch.ch/reatch.ch/vendor/craftcms/cms/src/web/Application.php(274): yii\base\Module->runAction('sprout-base-red...', Array)
#8 /home/httpd/vhosts/reatch.ch/reatch.ch/vendor/craftcms/cms/src/web/Application.php(577): craft\web\Application->runAction('sprout-base-red...', Array)
#9 /home/httpd/vhosts/reatch.ch/reatch.ch/vendor/craftcms/cms/src/web/Application.php(253): craft\web\Application->_processActionRequest(Object(craft\web\Request))
#10 /home/httpd/vhosts/reatch.ch/reatch.ch/vendor/yiisoft/yii2/base/Application.php(386): craft\web\Application->handleRequest(Object(craft\web\Request))
#11 /home/httpd/vhosts/reatch.ch/reatch.ch/web/index.php(22): yii\base\Application->run()
#12 {main}
2021-01-27 14:07:48 [-][1][a4254be4bf366ba929230bda31ea5b4e][info][application] $_GET = [
    'p' => 'admin/sprout-redirects/redirects/edit/38112'
]

$_POST = [
    'CRAFT_CSRF_TOKEN' => '••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••'
    'action' => 'sprout-base-redirects/redirects/save-redirect'
    'redirectId' => '38112'
    'redirect' => '50c9e2a1b68122b15444c20d8f14653012da88b831ad62e0b21a06a49bd84d81sprout-redirects/redirects'
    'siteId' => '1'
    'pluginHandle' => 'sprout-redirects'
    'oldUrl' => 'de/content'
    'newUrl' => 'publikationen'
    'method' => '301'
    'matchStrategy' => 'regExMatch'
    'enabled' => '1'
]

**Comment by tonioseiler** [comment]
Uncommented line 218 of RedirectsController
`
      //SproutBaseRedirects::$app->redirects->remove404RedirectIfExists($redirect);
`

Then it seems to work

**Comment by BenParizek** [comment]
This has been resolved in the latest version of Sprout Redirects.

The bug was within that line you commented out.

Related: https://github.com/barrelstrength/craft-sprout-seo/issues/233
