### ISSUE TITLE
Settings aren't saved to project configuration

### ISSUE THREAD

**Issue by gglnx** [barrelstrength/craft-sprout-redirects#36]
### Description (screenshots, logs, ...)

If I change the plugin name or enable 404 tracking in the settings in my development environment aren't saved to the project configuration and missing after deployment in my production environment.

### Steps to reproduce

1. Change some settings like plugin name or enable 404 tracking
2. Watch project configuration for changes

### Additional info

- Craft version: 3.6.15
- PHP version: 7.4.16
- Database driver & version: MySQL 8.0.23
- Plugins & versions: Sprout Redirects 1.5.3

_For some issues, we may request that you send the following items to Support <sprout@barrelstrengthdesign.com>. If you feel your issue may fall in that category, feel free to send things over after you post this issue and reference the issue in your email._

- `composer.json`
- `storage/logs/web.log` (or a zip of the whole log folder)
- An export of your database (or, if you can't share the whole db, the specific Sprout tables)

**Comment by BenParizek** [comment]
@gglnx This behavior is not supported yet but will be added in our next major release, which I'm working on now. I'll update this thread once I get it out.

**Comment by BenParizek** [comment]
This is now supported in the Craft 4 release:
https://plugins.craftcms.com/sprout-redirects?craft4
