### ISSUE TITLE
Can't upgrade to Pro version - The file or directory to be published does not exist

### ISSUE THREAD

**Issue by anchovy** [barrelstrength/craft-sprout-redirects#37]
### Description (screenshots, logs, ...)
Clicking on upgrade throws an error:
```
The file or directory to be published does not exist: ..../vendor/barrelstrength/sprout-base-redirects/src/web/assets/base/dist
```

### Steps to reproduce

1. Install the plugin
2. Goto 'Sprout Redirects' > 'Settings' and click the 'Upgrade to Pro' green button.

### Additional info

- Craft version: Craft Pro 3.5.19.1
- PHP version: 7.4.16
- Database driver & version:  MySQL 5.7.32
- Plugins & versions: Sprout Redirects  1.5.3

_For some issues, we may request that you send the following items to Support <sprout@barrelstrengthdesign.com>. If you feel your issue may fall in that category, feel free to send things over after you post this issue and reference the issue in your email._

- `composer.json`
- `storage/logs/web.log` (or a zip of the whole log folder)
- An export of your database (or, if you can't share the whole db, the specific Sprout tables)

**Comment by BenParizek** [comment]
Thanks for reporting @anchovy 

I'll get a release out to fix this shortly. In the meantime, you can go directly to the plugin store to upgrade:

https://plugins.craftcms.com/sprout-redirects

OR 

https://yourdomain.com**/plugin-store/sprout-redirects**

That page that is not loading is just an overview page that links to the plugin store.

**Comment by anchovy** [comment]
Hi @BenParizek 
So we've got a license now - how do I upgrade, do I need to add the license key to a config file or something?
There's no license key field in Settings > Plugins for the Sprout Redirects?

**Comment by BenParizek** [comment]
@anchovy If the Plugin lists shows a [Pro] badge next to the Redirects plugin you should see a license field. If not, maybe try using the Craft Utilities tab to clear template caches. Sometimes templates in the CP can be cached after updates and not reflect all the changes you'd expect to see.
