### ISSUE TITLE
Craft 4 Support

### ISSUE THREAD

**Issue by BenParizek** [barrelstrength/craft-sprout-redirects#39]
Sprout Redirects is in the process of being updated to Craft 4. Please see the statement in our docs for additional details:
https://sprout.barrelstrengthdesign.com/docs/support/road-map.html

Follow this thread if you'd like to be notified when the upgrade is ready.

**Comment by vandres** [comment]
@BenParizek Any news on this?

**Comment by heycactus** [comment]
@BenParizek any closer?

**Comment by Dean-Wilson** [comment]
@BenParizek any closer?

**Comment by BenParizek** [comment]
Craft 4 support for the Redirects plugin is now available:
https://plugins.craftcms.com/sprout-redirects?craft4

While there are significant changes under the hood, there are no major changes in the key functionality. For a list of everything that changed you can review the Update Guide here:
https://sprout.barrelstrengthdesign.com/docs/craft-v4/updates/4.44.444-redirects.html
